### ISSUE TITLE
有没有插件版的日程计划？

### ISSUE THREAD

**Issue by SokWith** [Harry-zklcdc/bing-lib#1]
自从NewBingGoGo插件版弃更了后，更方便电脑使用的浏览器插件版bing/openai就难觅了。、
现在bing可以直接做api了，大佬有没有做插件版的日程计划？

另外，有没有稳定可靠使用API的钉钉、微信机器人项目？

**Comment by Harry-zklcdc** [comment]
~~新建文件夹~~

**Comment by Harry-zklcdc** [comment]
机器人项目我用的是 Koishi框架

**Comment by SokWith** [comment]
![image](https://github.com/Harry-zklcdc/bing-lib/assets/129967025/d18bb112-1283-4184-8c98-11033b05a0dc)
NewbingGOGO插件版对桌面端浏览器很有用，我只能简单抢救了一点点。使用的是过了认证的cookie，还只有平衡模式。
期望能够完全拯救回来。
![image](https://github.com/Harry-zklcdc/bing-lib/assets/129967025/c63838d5-2cf8-4731-b17c-45cbcfec21e9)

**Comment by Harry-zklcdc** [comment]
之后在这跟踪进度: https://github.com/Harry-zklcdc/go-proxy-bingai/issues/391
